INTRODUCTION = """WE'VE STOLEN A YELLOW CAR. WE NEED TO GET IT HOME.
THE CAR IS SPECIAL.
THAT'S WHY THE GOVERNMENT WANTS IT.
WE CAN'T LET THEM HAVE IT.
ONE GOAL: SURVIVAL... AND THE CAR
REACH THE SAFEHOUSE BEFORE THE MAN GON GETCHU.
"""

CHOICES = """
    --- Your Choices ---
    A. Eat a tofu
    B. Drive moderately
    C. Speed ahead at full speed!
    D. Stop to refuel.
    E. Current status.
    Q. Quit the game.
    ---
"""

REFUEL = "-------You filled the fuel tank.------- The agents have gotten closer"

EAT_TOFU = """"--------Mmmmm soybean goodness.
--------You hunger is sated
"""

NO_TOFU = """--------You have no tofu left. 😢
"""

SEVERE_HUNGER = """********Your stomach rumbles.
********You need to eat something quick
"""

HUNGER = """********Your hunger is small but manageable.
"""

ENDGAME_TEXT = [
    """Game has ended. Thanks for playing!""",  # Quit the game
    """\n\nTHE AGENTS HAVE CLOSED IN ON YOU. 
THERE ARE AT LEAST 20 CARS SURROUNDING YOU. 
THE LEAD CAR BUMPS YOUR PASSENGER SIDE 
YOU MANAGE TO CORRECT YOUR STEERING 
TO KEEP YOU FROM CRASHING 

YOU DIDN'T SEE THE AGENT'S CAR RIGHT BESIDE YOU. 
THAT DRIVER BUMPS YOUR CAR. 
AND THAT'S IT.

YOU SPIN UNCONTROLLABLY. 
YOUR CAR FLIPS OVER AT LEAST TWO TIMES. 
OR MORE... YOU SEEM TO HAVE LOST COUNT. 

SIRENS. 

"ARE THEY ALIVE? THEY SAY AS YOU HEAR 
FOOTSTEPS COMING CLOSER. 
"DOESN'T MATTER, ALL WE WANTED WAS THE CAR"

YOU SEE A DOG SLOWLY STEP OUT OF THE OVERTURNED CAR. 

"YOU WILL NEVER STOP THE REVOLUTION!"
THE DOG SEEMS TO SAY TO THE AGENTS. 

IT WAS IN THE CAR THE WHOLE TIME. 

YOU DRIFT OFF INTO UNCONSCIOUSNESS...

--GAME OVER--\n""",  # Agents have caught up
    """\n\nYOUR CAR SPUTTERS AND SEEMS TO LET OUT 
A BIG SIGH.
THERES NO MORE FUEL LEFT.
    
THE AGENTS SURROUND YOU AND STEP OUT
OF THEIR CARS. THE LEAD AGENT RIPS
THE DOOR OPEN AND THROWS YOU OUT THE OF
THE CAR.
    
"WE FINALLY GOT IT"
    
YOU FAILED. 
    
--GAME OVER--""",  # Lose - run out of fuel/charge
    """\n\nYOUR STOMACH IS EMPTY.
WHO KNEW THAT WHAT THE DOCTOR SAID WAS TRUE,
THAT HUMAN/ROBOT HYBRIDS WOULD NEED
TOFU TO SUSTAIN THEMSELVES.
YOUR ROBOT SYSTEMS START TO SHUT DOWN.
YOUR HUMAN EYES CLOSE.
THE LAST THING THAT YOU HEAR ARE SIRENS.
THEY GOTCHU. THEY GOT THE CAR.
WE FAILED...
----GAME OVER----
""",  # Died of lack of sustenance
    """YOU PRESSED THR BUTTON TO OPEN THE GATE.
THIS ISN'T THE FIRST TIME YOU'VE DONE THIS.
YOU CAN TIME IT PERFECTLY SO THAT YOU
SLIDE THE CAR IN AS THE GATES CLOSE.

YOU KNOW YOU DID THE RIGHT THING.
THE GOVERNMENT WOULD HAVE TORN THE CAR APART.
ANALYZING IT,TESTING IT, THEN DESTROYING IT.

THEY DON'T KNOW ITS SECRETS...
THAT IT HOLDS THE KEY TO DIFFERENT WORLD.

AS YOU STEP OUT THE VEHICLE, FIDO RUNS UP TO YOU.
"THANK YOU FOR SAVING ME, HE SAYS.

AS YOU TAKE A COUPLE OF STEPS AWAY FROM THE CAR,
IT MAKES A STRANGE NOISE.

BEFORE YOUR EYES, IT SHIFTS ITS SHAPE.
YOU'VE SEEN THIS BEFORE, BUT ONLY IN
THE MOVIES.

"BUMBLEBEE...?"

----GAME OVER----
""",  # WIN
]
